env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - LD_LIBRARY_PATH=/home/runner/work/osxcross/target/binaries/lib 


builds:
  - id: regen-windows-amd64
    binary: regen
    main: ./app/regen
    goarch:
      - amd64
      # - arm
    # goarm:
    #   - 6
    #   - 7
    goos:
      - windows
    env:
      - CC=/usr/bin/x86_64-w64-mingw32-gcc
      - CXX=/usr/bin/x86_64-w64-mingw32-g++
      - PKG_CONFIG_PATH=/mingw64/lib/pkgconfig
      # - CROSS_COMPILE=arm-linux-gnueabi
      # - CC=/usr/bin/arm-linux-gnueabi-gcc-9 
      # - CXX=/usr/bin/arm-linux-gnueabi-g++-9
      - CROSS_COMPILE=/home/runner/work/osxcross/target/target/bin/arm_binaries/arm-linux-gnueabi-
      - CC=/home/runner/work/osxcross/target/target/bin/arm_binaries/arm-linux-gnueabi-gcc-7
      - CXX=/home/runner/work/osxcross/target/target/bin/arm_binaries/arm-linux-gnueabi-g++-7
    # env:
    #   - CC=aarch64-w64-mingw32-gcc
    #   - CXX=aarch64-w64-mingw32-g++
      # - CC=/home/runner/work/osxcross/target/target/bin/x86_64-w64-mingw32-gcc
      # - CXX=/home/runner/work/osxcross/target/target/bin/x86_64-w64-mingw32-g++
      # - CC=x86_64-w64-mingw32-gcc
      # - CXX=x86_64-w64-mingw32-g++
    flags:
      - -tags="netgo ledger"
      - -trimpath
      - -mod=readonly   
      - -buildmode=exe
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=regen -X github.com/cosmos/cosmos-sdk/version.AppName=regen -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"
      - -linkmode=external

  - id: regen-darwin-amd64
    binary: regen
    main: ./app/regen
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=/home/runner/work/osxcross/target/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/target/bin/o64-clang++
    flags:
      - -tags="netgo ledger"
      - -trimpath
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=regen -X github.com/cosmos/cosmos-sdk/version.AppName=regen -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"

  - id: regen-linux-amd64
    binary: regen
    main: ./app/regen
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - -tags="netgo ledger"
      - -trimpath
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=regen -X github.com/cosmos/cosmos-sdk/version.AppName=regen -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"
 

archives:
  - id: regen
    builds:
      # - regen-windows-amd64
      - regen-windows-arm
      - regen-darwin-amd64
      - regen-linux-amd64   
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: zip
    files:
      - none*
brews:
  - name: regen-ledger
    ids: 
      - regen
    tap:
      owner: regen-network
      name: homembrew-tap
    homepage: "https://www.regen.network/"
    description: "Blockchain-powered marketplace for climate solutions and planetary regenerations"
    custom_block: |
      head "https://github.com/regen-network/regen-ledger.git"
    test: |
      system "#{bin}/regen--version"
    install: |
      bin.install "regen"
release:
  github:
    owner: regen-network
    name: regen
  prerelease: auto
  draft: false
