name: goreleaser

on: [push]
  # pull_request:
  # push:
  #   tags:
  #     - '*'

jobs:
  goreleaser:

    runs-on: ubuntu-latest

    steps:
      -
        name: Windows dependencies
        run: |
          sudo apt install binutils-mingw-w64
          sudo apt-get install gcc-mingw-w64-x86-64
          echo "==========================="
          whereis x86_64-w64-mingw32-gcc
          whereis x86_64-w64-mingw32-g++
          echo "==========================="
          ls /usr/bin
      -
        name: GCC multilib
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib clang 
          
      -
        name: OSXCross for CGO Support
        run: |
          mkdir ../../osxcross
          git clone https://github.com/likhita-809/osxcross-target.git ../../osxcross/target
          sudo cp /home/runner/work/osxcross/target/target/lib/libcrypto.so.1.0.0 /usr/lib/x86_64-linux-gnu
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
