name: goreleaser

on: [push]
  # pull_request:
  # push:
  #   tags:
  #     - '*'

jobs:
  goreleaser:

    runs-on: ubuntu-latest

    steps:
      # -
      #   name: Windows dependencies
      #   run: |
      #     sudo apt install binutils-mingw-w64
      #     sudo apt-get install gcc-mingw-w64-x86-64
      #     sudo apt-get install g++-mingw-w64-x86-64
      #     echo "==========================="
      #     whereis x86_64-w64-mingw32-gcc
      #     whereis x86_64-w64-mingw32-g++
      #     echo "==========================="
      #     ls /usr/lib

# sudo cp /home/runner/work/osxcross/target/target/lib/libcrypto.so.1.0.0 /usr/lib/x86_64-linux-gnu
#           sudo cp /home/runner/work/osxcross/target/target/lib/x86_64-w64-mingw32-ld /usr/lib/x86_64-w64-mingw32-ld         


      -
        name: Install arm dependencies
        run: |
          sudo apt-get install gcc g++
          sudo apt-get install gcc-arm-linux-gnueabi g++-arm-linux-gnueabi

      -
        name: GCC multilib
        run: |
          sudo apt-get update
          sudo apt-get install --reinstall build-essential
          sudo apt-get install gcc-multilib g++-multilib clang 
      -
        name: OSXCross for CGO Support
        run: |
          mkdir ../../osxcross
          git clone https://github.com/likhita-809/osxcross-target.git ../../osxcross/target
          sudo ln -s /home/runner/work/osxcross/target/target/lib/libcrypto.so.1.0.0 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
          echo "========================"
          whereis aarch64-w64-mingw32-gcc
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
